version: '3.8'

services:

  patient-management-db:
    image: postgres:15
    container_name: patient-management-db

    environment:
      POSTGRES_DB: patient_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - patient_management_data:/var/lib/postgresql/data

  auth-service-db:
    image: postgres:15
    container_name: auth-service-db

    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - "5001:5432"

    volumes:
      - auth_service_data:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper

    ports:
      - "2181:2181"

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper


  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile

    container_name: billing-service

    ports:
      - "4001:4001"
      - "9001:9001"

    depends_on:
      - kafka

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile

    container_name: analytics-service

    ports:
      - "4002:4002"

    depends_on:
      - kafka

    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  patient-management:
    build:
      context: ./patient-management
      dockerfile: Dockerfile

    container_name: patient-management

    depends_on:
      - patient-management-db
      - billing-service
      - kafka

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-management-db:5432/patient_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password

      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

    container_name: api-gateway

    ports:
      - "4004:4004"

    depends_on:
      - patient-management
      - auth-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile

    container_name: auth-service

    ports:
      - "4005:4005"

    depends_on:
      - auth-service-db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/auth_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: ${JWT_SECRET}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always


volumes:
  patient_management_data:
  auth_service_data: