spring.application.name=patient-management

spring.datasource.url=jdbc:postgresql://localhost:5432/patient_management
spring.datasource.username=admin
spring.datasource.password=password

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=admin
#spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

server.port=4000

logging.level.root=info

billing.service.address=billing-service
billing.service.grpc.port=9001

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.kafka.bootstrap-servers=kafka:9092